#!/usr/bin/env bash
#a script print that displays bad luck for the 4 iteration and good luck for the 8th loop. 
n=1
while [ "$n" -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
	elif [ $n == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
