#!/usr/bin/env bash
#a Bash script that gives you information about the holbertonschool file
filename="school_file"

if [ -e "$filename" ]
then
    echo "school file exists"

    if [ -s "$filename" ]
    then
        echo "school file is empty"
    else
        echo "shool file is not empty"
    fi

    if [ -f "$filename" ]
    then
        echo "school_file is a regular file"
    fi
else
    echo "school file does not exist"
fi
